name: OpTimes
description: "A Work Timer."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  pdf: ^3.12.0
  printing: ^5.14.3
  share_plus: ^13.1.0
  path_provider: ^2.1.5
  url_launcher: ^6.3.2
  flutter_slidable: ^4.0.3
  file_picker: ^3.0.4
  archive: ^3.6.1
  receive_sharing_intent: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png